<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-7R2TGVRQ" failures="1" tests="2" name="LoginTest" time="107.495" errors="0" timestamp="2022-08-07T20:08:55 IST">
  <testcase classname="realtimeproject.LoginTest" name="login" time="41.983"/>
  <testcase classname="realtimeproject.LoginTest" name="login" time="2.855">
    <failure type="java.lang.AssertionError" message="expected [failure] but found [successfull]">
      <![CDATA[java.lang.AssertionError: expected [failure] but found [successfull]
at realtimeproject.LoginTest.login(LoginTest.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- LoginTest -->
