<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-7R2TGVRQ" failures="1" tests="4" name="Test" time="104.359" errors="0" timestamp="2022-08-07T18:49:17 IST">
  <testcase classname="realtimeproject.TwoTest" name="twoTest" time="0.018"/>
  <testcase classname="realtimeproject.LoginTest" name="login" time="29.821"/>
  <testcase classname="realtimeproject.LoginTest" name="login" time="2.144">
    <failure type="java.lang.AssertionError" message="expected [failure] but found [successfull]">
      <![CDATA[java.lang.AssertionError: expected [failure] but found [successfull]
at realtimeproject.LoginTest.login(LoginTest.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="realtimeproject.FirstTest" name="firstTest" time="0.002"/>
</testsuite> <!-- Test -->
